[tools]
# Python versions
python = {version="3.10"}
python.latest = "3.10"

# Node.js
node = {version="lts"}

# PostgreSQL
postgres = {version="14"}
postgres.latest = "16.1"

# MySQL
mysql = {version="5.7"}
mysql.latest = "8.0.35"

# Go
go = {version="latest"}

[env]
# Add any environment variables you need
PATH.prepend = "{{ env.HOME }}/.local/bin" 