[tools]
# Python versions
python = { version = "3.10", latest = "3.10" }

# Node.js
node = { version = "lts", latest = "20" }

# PostgreSQL
postgres = { version = "14", latest = "16.1" }

# MySQL
mysql = { version = "5.7", latest = "8.0.35" }

# Go
go = { version = "latest" }

[env]
# Add environment variables
PATH = ["{{ env.HOME }}/.local/bin", "{{ env.PATH }}"]

[settings]
experimental = true
verbose = false 