[tools]
# Python versions
python = { version = "3.10" }

# Node.js
node = { version = "lts", latest = "20" }

# PostgreSQL
postgres = { version = "16.1", latest = "16.1" }

# MySQL
mysql = { version = "5.7", latest = "8.0.35" }

# Go
go = { version = "latest" }

# Ruby
ruby = { version = "3.2.2" }

[settings]
experimental = true
verbose = false 